#!bin/bash

set -x

sed -i "s/bind-address.*/bind-address = $DB_HOST/" /etc/mysql/mariadb.conf.d/50-server.cnf

mysql_install_db --user=mysql --datadir=/var/lib.mysql

{
	echo "FLUSH PRIVILEGES;
	CREATE DATABASE IF NOT EXISTS $DB_NAME;
	CREATE USER IF NOT EXISTS '$DB_USER@'%' IDENTIFIED BY '$DB_PW';
	GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';
	FLUSH PRIVILEGES;"
} | mysqld --bootstrap
	# ALTER USER 'root'@'localhost' IDENTIFIED BY '$ROOT_PW';

exec "$@"
