#!bin/bash

set -x

mysql_install_db --user=mysql --datadir=/var/lib/mysql

sed -i "s/bind-address.*/bind-address = $DB_HOST/" /etc/mysql/mariadb.conf.d/50-server.cnf

{
	echo "FLUSH PRIVILEGES;"
	echo "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
	echo "CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PW';"
	echo "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';"
	echo "FLUSH PRIVILEGES;"
} | mysqld --bootstrap
	# ALTER USER 'root'@'localhost' IDENTIFIED BY '$ROOT_PW';

exec "$@"
