#!bin/bash

set -x

echo "starting deamon"
/usr/sbin/mysqld --user=mysql --skip-networking --default-time-zone=SYSTEM --wsrep_on=OFF \
		--expire-logs-days=0 \
		--loose-innodb_buffer_pool_load_at_startup=0 > /dev/null &
MDB_PID=$!
# sleep 10

echo "this is PID: $MDB_PID"


cat << STOP > /tmp/dbSetup.sql
	CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;\
	CREATE USER IF NOT EXISTS '$WP_USER'@'%' IDENTIFIED BY '$WP_PASSWORD';\
	GRANT ALL PRIVILEGES ON $WP_DB_NAME.* TO '$WP_USER'@'%';\
	ALTER USER 'root'@'localhost' IDENTIFIED BY '$ROOT_PW';\
	FLUSH PRIVILEGES;\
STOP

echo "------testing sql file----"
cat /tmp/dbSetup.sql
echo "----done---"

mysql < /tmp/dbSetup.sql > /devnull

# echo "stopping deamon"

kill $MDB_PID
wait $MDB_PID
echo "start sql"
sed -i "s|skip-networking|# skip-networking|g" /etc/mysql/mariadb.conf.d/50-server.cnf
sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/mysql/mariadb.conf.d/50-server.cnf
# mysqld_safe --user-mysql

mysqld --user=mysql --bootstrap < /tmp/dbSetup.sql
exec /usr/sbin/mysqld --user=mysql > /dev/null